---
project: Field Demo
kind: PIPELINE
name: Add Kubernetes Endpoint to Cloud Assembly - Token
icon: organization,left, is-purple
enabled: true
description: Add a Kubernetes Endpoint to Cloud Assembly using Token Based authentication
concurrency: 10
input:
  clusterAddress: ''
  clusterCACertificate: ''
  clusterName: ''
  clusterUserToken: ''
_inputMeta:
  clusterCACertificate:
    mandatory: true
    description: ''
  clusterUserToken:
    mandatory: true
    description: ''
  clusterName:
    mandatory: true
    description: ''
  clusterAddress:
    mandatory: true
    description: ''
workspace:
  endpoint: smcg-sc2-docker-host - TLS
  image: sammcgeown/codestream-ci-k8s:latest
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Main
stages:
  Main:
    taskOrder:
    - Authenticate
    - CreateEndpoint
    tasks:
      Authenticate:
        type: Pipeline
        input:
          pipeline: vra-authenticateUser
          inputProperties:
            vraFQDN: ${var.vraFQDN}
            vraUserName: ${var.vraUsername}
            vraUserPassword: ${var.vraPassword}
      CreateEndpoint:
        type: Pipeline
        input:
          pipeline: vra-POST
          inputProperties:
            vraAccessToken: ${Main.Authenticate.output.outputProperties.vraAccessToken}
            vraRequestPayload: '{     "name": "${input.clusterName}",     "description": "MOAD Kubernetes
              Cluster (${input.clusterName})",     "address": "${input.clusterAddress}",     "credentials":
              {         "privateKey": "${input.clusterUserToken}",         "type": "Bearer"     },     "clusterType":
              "EXTERNAL",     "caCertificate": "${input.clusterCACertificate}",     "shared": "true",     "global":
              "true" }'
            vraRequestUri: https://${var.vraFQDN}/cmx/api/resources/k8s/clusters/
