---
project: Field Demo
kind: PIPELINE
name: Learn Code Stream - Notifications
icon: organization,left, is-purple
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: REST
        input:
          action: get
          url: https://v2.jokeapi.dev/joke/Any?blacklistFlags=nsfw,religious,political,racist,sexist,explicit
          headers:
            Accept: application/json
            Content-Type: application/json
          payload: ''
notifications:
  webhook:
  - url: https://hooks.slack.com/services/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
    action: post
    payload: |-
      {
         "attachments":[
            {
               "fallback":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}> ${status}",
               "pretext":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}>",
               "color":"#0042D0",
               "fields":[
                  {
                     "title":"Details",
                     "value":"Pipeline: ${name} (Execution ID: ${executionId})\nExecution Index: ${executionIndex}\nUser: ${requestBy}\nStatus: ${statusMessage}",
                     "short":false
                  }
               ]
            }
         ]
      }
    event: STARTED
    stage: Stage0
  - url: https://hooks.slack.com/services/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
    action: post
    payload: |-
      {
         "attachments":[
            {
               "fallback":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}> ${status}",
               "pretext":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}>",
               "color":"#00D01B",
               "fields":[
                  {
                     "title":"Details",
                     "value":"Pipeline: ${name} (Execution ID: ${executionId})\nExecution Index: ${executionIndex}\nUser: ${requestBy}\nStatus: ${statusMessage}",
                     "short":true
                  }
               ]
            }
         ]
      }
    event: SUCCESS
    stage: Stage0
  - url: https://hooks.slack.com/services/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
    action: post
    payload: |-
      {
         "attachments":[
            {
               "fallback":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}> ${status}",
               "pretext":"[vra8-test-ga] <${executionUrl}|${name}#${executionIndex}>",
               "color":"#D00000",
               "fields":[
                  {
                     "title":"Details",
                     "value":"Pipeline: ${name} (Execution ID: ${executionId})\nExecution Index: ${executionIndex}\nUser: ${requestBy}\nStatus: ${statusMessage}",
                     "short":false
                  }
               ]
            }
         ]
      }
    event: FAILURE
    stage: Stage0
