---
project: Field Demo
kind: PIPELINE
name: MOAD - Deploy OpenCart Kubernetes
icon: organization,left, is-pink
enabled: true
concurrency: 10
input:
  OpenCartAdminPassword: VMware1!
  OpenCartAdminUserName: ocuser
  OpenCartDatabasePassword: VMware1!
_inputMeta:
  OpenCartDatabasePassword:
    mandatory: true
    description: ''
  OpenCartAdminUserName:
    mandatory: true
    description: OpenCart Admin User Name
  OpenCartAdminPassword:
    mandatory: true
    description: OpenCart Admin Password
workspace:
  endpoint: smcg-sc2-docker-host - TLS
  image: python
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Deploy-MySQL
- Deploy-OpenCart
stages:
  Deploy-MySQL:
    taskOrder:
    - MySQL Server
    - Generate vRNI Traffic
    tasks:
      MySQL Server:
        type: Blueprint
        input:
          action: CreateDeployment
          blueprint: OpenCart DB Server
          deploymentName: oc-db-${executionId}
          parameters:
            image: Ubuntu-18
            environment: vSphere
            password: ${input.OpenCartAdminPassword}
            size: medium
            monitoring: telegraf
            username: ${input.OpenCartAdminUserName}
          version: '5'
          filepath: ''
          apiToken: ${var.MOAD-API-Token}
      Generate vRNI Traffic:
        type: REST
        preCondition: '"true" == "false"'
        input:
          action: post
          url: https://j2-vrni.eng.vmware.com/job/generate_custom_flows/buildWithParameters?src_ips=95.79.45.2-95.79.45.10&dst_ips=${Deploy-MySQL.MySQL
            Server.output.deploymentDetails.resources.mysql.address}&src_ports=10000&dst_ports=3306&collector_ips=10.196.164.26&protocol=tcp&source_types=VDS_IPFIX&time=3600&branch=master&USE_SCAPY=false&site=SiteT&rule_id=1001&flow_action=Allow
          headers:
            Accept: application/json
            Content-Type: application/json
            Authorization: Basic bXNtaXQ6MTExMDBkMTExNzM4YWUxY2I4YmRlYjliNzUwOTFiMDRmYg==
          payload: ''
  Deploy-OpenCart:
    taskOrder:
    - EncodeAdminPassword,EncodeDBPassword
    - Deploy OpenCart
    tasks:
      EncodeAdminPassword:
        type: Custom
        input:
          name: Base64Encode
          version: '0.1'
          properties:
            stringToEncode: ${input.OpenCartAdminPassword}
      EncodeDBPassword:
        type: Custom
        input:
          name: Base64Encode
          version: '0.1'
          properties:
            stringToEncode: ${input.OpenCartDatabasePassword}
      Deploy OpenCart:
        type: K8S
        ignoreFailure: true
        endpoints:
          scm: OpenCart
          kubernetesServer: sm-01-87b76193-8fad-4bba-a38c-84aaae2104c3
        input:
          action: CREATE
          timeout: 5
          continueOnConflict: false
          filePath: kubernetes/00-opencart.yaml
          scmConstants:
            OCINSTANCE: ${executionId}
            DBPASSWORD: ${Deploy-OpenCart.EncodeDBPassword.output.properties.encodedString}
            OCUSER: ${input.OpenCartAdminUserName}
            DBHOST: ${Deploy-MySQL.MySQL Server.output.deploymentDetails.resources.mysql.address}
            OCPASSWORD: ${Deploy-OpenCart.EncodeAdminPassword.output.properties.encodedString}
          yaml: ''
