---
project: Field Demo
kind: PIPELINE
name: vra-CreateVariable
icon: organization,left, is-purple
enabled: true
tags: [
  vra,
  variable,
  api,
  codestream]
concurrency: 10
input:
  Name: ''
  Project: Field Demo
  Type: ''
  Value: ''
_inputMeta:
  Project:
    mandatory: true
    description: ''
  Type:
    mandatory: true
    description: SECRET | REGULAR | RESTRICTED
  Value:
    mandatory: true
    description: ''
  Name:
    mandatory: true
    description: ''
output:
  variableId: ${Main.CreateVariable.output.outputProperties.vraResponseJson.id}
workspace:
  endpoint: smcg-sc2-docker-host - TLS
  image: sammcgeown/codestream-ci-k8s:latest
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Main
stages:
  Main:
    taskOrder:
    - Authenticate
    - CreateVariable
    tasks:
      CreateVariable:
        type: Pipeline
        input:
          pipeline: vra-POST
          inputProperties:
            vraAccessToken: ${Main.Authenticate.output.outputProperties.vraAccessToken}
            vraRequestPayload: '{ "project": "${input.Project}", "kind": "VARIABLE", "name": "${input.Name}",
              "description": "${input.Name} - vra-CreateVariable", "type": "${input.Type}", "value": "${input.Value}"
              }'
            vraRequestUri: https://${var.vraFQDN}/pipeline/api/variables
      Authenticate:
        type: Pipeline
        input:
          pipeline: vra-authenticateUser
          inputProperties:
            vraFQDN: ${var.vraFQDN}
            vraUserName: ${var.vraUsername}
            vraUserPassword: ${var.vraPassword}
