---
project: Field Demo
kind: PIPELINE
name: vra-GetVariable
icon: organization,left, is-purple
enabled: true
tags: [
  vra,
  variable,
  api,
  codestream]
concurrency: 10
input:
  Name: ''
  Project: Field Demo
_inputMeta:
  Project:
    mandatory: true
    description: ''
  Name:
    mandatory: true
    description: ''
output:
  variableValue: ${Main.GetVariableById.output.outputProperties.vraResponseJson.value}
workspace:
  endpoint: smcg-sc2-docker-host - TLS
  image: sammcgeown/codestream-ci-k8s:latest
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Main
stages:
  Main:
    taskOrder:
    - Authenticate
    - GetVariables
    - FilterByNameAndProject
    - GetVariableById
    tasks:
      GetVariableById:
        type: Pipeline
        input:
          pipeline: vra-GET
          inputProperties:
            vraAccessToken: ${Main.Authenticate.output.outputProperties.vraAccessToken}
            vraRequestPayload: ''
            vraRequestUri: https://${var.vraFQDN}/pipeline/api/variables/${Main.FilterByNameAndProject.output.exports.variableId}
      FilterByNameAndProject:
        type: CI
        input:
          steps:
          - ''
          - echo '${Main.GetVariables.output.outputProperties.vraResponseJson}' > variables.json
          - ''
          - export variableId=$(jq '.documents[] | select(.project=="${input.Project}") | select(.name=="${input.Name}")'
            variables.json | jq -r '.id')
          export:
          - variableId
          artifacts: [
            ]
          process: [
            ]
      Authenticate:
        type: Pipeline
        input:
          pipeline: vra-authenticateUser
          inputProperties:
            vraFQDN: ${var.vraFQDN}
            vraUserName: ${var.vraUsername}
            vraUserPassword: ${var.vraPassword}
      GetVariables:
        type: Pipeline
        input:
          pipeline: vra-GET
          inputProperties:
            vraAccessToken: ${Main.Authenticate.output.outputProperties.vraAccessToken}
            vraRequestPayload: ''
            vraRequestUri: https://${var.vraFQDN}/pipeline/api/variables
