---
project: Field Demo
kind: PIPELINE
name: vrops-authenticateUser
icon: organization,left, is-warning is-solid
enabled: true
concurrency: 10
input:
  vropsAuthSource: Local
  vropsFQDN: ''
  vropsUserName: ''
  vropsUserPassword: ''
_inputMeta:
  vropsFQDN:
    mandatory: true
    description: vRealize Operations FQDN - e.g. vrops-fielddemo.cmbu.local
  vropsUserName:
    mandatory: true
    description: 'vRealize Operations User in UPN format - e.g: ''user@domain.local''. For local accounts,
      omit the domain - e.g. ''configuser'''
  vropsAuthSource:
    mandatory: true
    description: vRealize Operations Auth Source
  vropsUserPassword:
    mandatory: true
    description: vRealize Operations User Password
output:
  vropsAccessToken: ${authUser.Authenticate.output.responseJson.token}
workspace:
  endpoint: smcg-sc2-docker-host - TLS
  image: sammcgeown/codestream-ci
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- authUser
stages:
  authUser:
    taskOrder:
    - Authenticate
    tasks:
      Authenticate:
        type: REST
        input:
          action: post
          url: https://${input.vropsFQDN}/suite-api/api/auth/token/acquire
          headers:
            Accept: application/json
            Content-Type: application/json
          payload: |-
            {
                "username": "${input.vropsUserName}",
                "authsource": "${input.vropsAuthSource}",
                "password": "${input.vropsUserPassword}",
                "others": [],
                "otherAttributes": {}
            }
